specification.pdf: specification.tex fdl.tex
	pdflatex specification
	pdflatex specification

all: specification.pdf

clean:
	rm -f fdl.aux
	rm -f specification.aux
	rm -f specification.out
	rm -f specification.log
	rm -f specification.pdf
