.\" -*-nroff-*-
.\"
.\" Copyright (C) 2010, 2011
.\" Martin Lambers <marlam@marlam.de>
.\"
.\" Copying and distribution of this file, with or without modification, are
.\" permitted in any medium without royalty provided the copyright notice and this
.\" notice are preserved. This file is offered as-is, without any warranty.
.TH GTA 1 2011-03
.SH NAME
gta \- a tool to manipulate Generic Tagged Array (GTA) files.
.SH DESCRIPTION
The \fBgta\fP tool provides a set of commands that manipulate GTAs on various
levels (element components, dimensions, arrays, or streams) and allow import
from and export to other file formats.
.SH USAGE
Use \fBgta help\fP to get a list of available commands, and
\fBgta help cmd\fP to get help for command \fBcmd\fP.
.br
(Alternatively, you can use \fBgta --help\fP and \fBgta cmd --help\fP.)
